services:
  postgres:
    image: postgres:17-alpine
    ports:
      - 5432:5432
    volumes:
      - db-data:/var/lib/postgresql/data:rw
    environment:
      - POSTGRES_PASSWORD=test
      - POSTGRES_USER=admin
      - POSTGRES_DB=la-ruche-citoyenne

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

volumes:
  db-data: